name: Publish docs
on:
  push:
    branches:
      - main
jobs:
  publish_docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v2
        with:
          python-version: 3.10.9
      - name: install dependencies
        run: pip3 install .[doc]
      - name: publish docs
        env:
          FLIT_USERNAME: __token__
          FLIT_PASSWORD: ${{ secrets.FLIT_PASSWORD }}
        run: bash scripts/publish_docs.sh