name: Publish project
on:
  release:
    types: [published]
jobs:
  publish_project:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: install flit
        run: pip3 install flit
      - name: publish project
        env:
          FLIT_USERNAME: __token__
          FLIT_PASSWORD: ${{ secrets.FLIT_PASSWORD }}
        run: flit publish